import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Bot,Building2,Radio,Users}from'lucide-react';import{mockEvents,type AgentEvent,type AgentStatus}from'./protocol/agent-event';import'./style.css';
const UP='https://raw.githubusercontent.com/zkblk/pixel-agents/main/public';
type Agent={id:string,name:string,provider:string,model:string,status:AgentStatus,task:string,tokens:number,skill:string,x:number,y:number,homeX:number,homeY:number,sprite:string,facing:string};
const seed:Agent[]=[
{id:'ux',name:'UX Agent',provider:'Codex',model:'GPT-5.6',status:'arriving',task:'Carpen · Customer flow',tokens:38400,skill:'UX Designer',x:67.5,y:48.9,homeX:25.8,homeY:71,sprite:'Frontend-dev-1',facing:'rear-left'},
{id:'research',name:'Research Agent',provider:'Claude Code',model:'Claude',status:'arriving',task:'Berg · HMI research',tokens:21700,skill:'Design Director',x:67.5,y:48.9,homeX:48.9,homeY:52.9,sprite:'Claude-1',facing:'rear-right'},
{id:'ui',name:'UI Agent',provider:'Codex',model:'GPT-5.6',status:'arriving',task:'AI Office · UI shell',tokens:14200,skill:'UI Designer',x:67.5,y:48.9,homeX:65.9,homeY:75.8,sprite:'dev-2',facing:'rear-right'}];
const fmt=(n:number)=>n>=1000?(n/1000).toFixed(1)+'k':String(n);
function applyEvent(list:Agent[],e:AgentEvent){return list.map(a=>{if(a.id!==e.agentId)return a;let status=a.status;if(e.type==='agent.started')status='arriving';if(e.type==='agent.working')status='working';if(e.type==='agent.waiting')status='waiting';if(e.type==='agent.finished')status='done';return{...a,status,provider:e.provider??a.provider,model:e.model??a.model,task:e.task??a.task,tokens:e.tokens??a.tokens,skill:e.skill??a.skill}})}
function App(){const[agents,setAgents]=useState(seed);const[selected,setSelected]=useState('ux');const[feed,setFeed]=useState<string[]>(['Office connected · metadata only']);
useEffect(()=>{const timers=mockEvents.map(e=>setTimeout(()=>{setAgents(v=>applyEvent(v,e));setFeed(v=>[e.type+' · '+e.agentId,...v].slice(0,4))},e.at));return()=>timers.forEach(clearTimeout)},[]);
useEffect(()=>{const t=setInterval(()=>setAgents(v=>v.map(a=>{let tx=a.homeX,ty=a.homeY;if(a.status==='waiting'){tx=73.5;ty=56.7}if(a.status==='done'){tx=67.5;ty=48.9}const dx=tx-a.x,dy=ty-a.y;if(Math.abs(dx)+Math.abs(dy)<.35)return a.status==='arriving'?{...a,x:tx,y:ty,status:'working'}:{...a,x:tx,y:ty};return{...a,x:a.x+dx*.08,y:a.y+dy*.08}})),70);return()=>clearInterval(t)},[]);
const a=agents.find(x=>x.id===selected)??agents[0];const active=agents.filter(x=>x.status!=='done').length,total=agents.reduce((s,x)=>s+x.tokens,0);return <div className="app"><header><b>DEVIES <span>AI OFFICE</span></b><nav>Office　 Board　 Timeline　 Reports</nav><i><Radio size={14}/> LIVE DEMO</i></header><aside><h5>BUILDING</h5><div className="active"><Building2/> Alexander's Studio</div><div><Users/> Design</div><div><Bot/> Development</div><h5>ROOMS</h5><div className="room">● AI Design Studio <small>{active}</small></div><div>○ Lounge</div><footer>zkblk · connected</footer></aside><main><section className="title"><div><small>DESIGN / FLOOR 01</small><h1>Alexander's Studio</h1></div><div className="pill">{active} agents online</div></section><section className="office"><img className="room-bg" src={UP+'/rooms/office-day.png'}/>{agents.map(x=><button key={x.id} className={'agent '+(selected===x.id?'selected ':'')+x.status} style={{left:x.x+'%',top:x.y+'%'}} onClick={()=>setSelected(x.id)}><span className="activity">{x.status==='waiting'?'☕':x.status==='done'?'✓':'•••'}</span><img className="sprite" src={UP+'/sprites/characters/'+x.sprite+'-'+x.facing+'.png'}/><label>{x.name}<em>{x.status}</em></label></button>)}<div className="event-feed">{feed.map((f,i)=><div key={i}>{f}</div>)}</div><div className="source-badge">PIXEL OFFICE ENGINE · EVENT DRIVEN</div></section><section className="stats"><div><b>{active}</b><small>ACTIVE AGENTS</small></div><div><b>{fmt(total)}</b><small>TOKENS TODAY</small></div><div><b>{agents.filter(x=>x.status==='working').length}</b><small>WORKING</small></div><div><b>{agents.filter(x=>x.status==='waiting').length}</b><small>WAITING</small></div></section></main><section className="inspect"><small>AGENT INSPECTOR</small><h2>{a.name}</h2><div className={'status '+a.status}>● {a.status}</div><dl><dt>Provider</dt><dd>{a.provider}</dd><dt>Model</dt><dd>{a.model}</dd><dt>Task</dt><dd>{a.task}</dd><dt>Tokens</dt><dd>{fmt(a.tokens)}</dd><dt>Skill</dt><dd>{a.skill}</dd></dl><div className="context"><span>Context</span><b>63%</b><progress value="63" max="100"/></div><p className="safe">Metadata only · No source code, prompts or chain-of-thought are transmitted.</p></section></div>}createRoot(document.getElementById('root')!).render(<App/>);